package gosync

type LogSeverity uint8

const (
	LogSeverityDebug LogSeverity = iota
	LogSeverityInfo
	LogSeverityWarn
	LogSeverityError
)

type LogEvent uint8

const (
	LogEventSynchronizationStarted LogEvent = iota
	LogEventSynchronizationCompleted
	LogEventChangeSynchronized
	LogEventConflictDetected
	LogEventRetryStarted
	LogEventRetryCompleted
	LogEventWarningRaised
	LogEventOperationFailed
	LogEventPersistentDestinationFailure
	LogEventConsoleDestinationFailure
	LogEventConfigurationStarted
	LogEventConfigurationSucceeded
	LogEventConfigurationCancelled
	LogEventConfigurationFailed
	LogEventBackupCycleStarted
	LogEventBackupArchiveVerified
	LogEventBackupArchiveConfirmed
	LogEventBackupRetentionApplied
	LogEventBackupCandidateRecovered
	LogEventBackupCycleFailed
	LogEventBackupCycleCompleted
	LogEventBackupOwnershipRejected
)
